name: app

type: php:8.1

dependencies:
  php:
    composer/composer: "^2"

build:
    flavor: none

# Static website usually don't require much ressources. See
# https://symfony.com/doc/current/cloud/cookbooks/resources_allocation.html
# for more information
size: XS
resources:
    base_memory: 64
    memory_ratio: 128

runtime:
  extensions:
    - ctype
    - iconv
    - apcu
    - mbstring
    - sodium
    - xsl
    - pdo_pgsql

web:
    locations:
        "/":
            root: "ecrire"
            index:
                - "index.php"
#            passthru: "/index.php"

#            scripts: false
            expires: 10m

hooks:
  build: |
    set -x -e

    composer install
  deploy: |
    set -x -e

#mounts:
#  "/local":
#    source: local
#    source_path: "local"
#  "/prive":
#    source: local
#    source_path: "prive"
#  "/ecrire":
#    source: local
#    source_path: "ecrire"
#  "/config":
#    source: local
#    source_path: "config"

disk: 2048
